name: Build OpenWrt for Banana Pi R4

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: "Kernel version"
        required: true
        default: "6.12"
        type: choice
        options:
          - "6.12"
          - "6.6"
          - "5.15"
      profile:
        description: "Device profile"
        required: true
        default: "bananapi_bpi-r4"
        type: choice
        options:
          - "bananapi_bpi-r4"
          - "bananapi_bpi-r4-poe"

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext zlib1g-dev swig unzip time rsync python3 python3-pip

    - name: Copy 8GB BL2/FIP files to OpenWrt
      run: |
        cp bpi-r4_sdmmc_8GB_bl2.img openwrt/
        cp bpi-r4_sdmmc_8GB_fip.bin openwrt/

    - name: Setup OpenWrt feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure OpenWrt for Banana Pi R4
      working-directory: openwrt
      run: |
        # Copy pre-configured file
        cp bpi-r4-8gb-config .config
        
        # Apply configuration
        make defconfig

    - name: Build OpenWrt
      working-directory: openwrt
      run: |
        # Build with 8GB BL2/FIP files
        cp bpi-r4_sdmmc_8GB_bl2.img staging_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/
        cp bpi-r4_sdmmc_8GB_fip.bin staging_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/
        
        make -j$(nproc) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-bpi-r4-8gb
        path: openwrt/bin/targets/mediatek/filogic/*
        retention-days: 7

    - name: Upload to Google Drive (optional)
      if: ${{ false }}
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.CREDENTIALS }}
        filename: "openwrt/bin/targets/mediatek/filogic/*.bin"
        folderId: ${{ secrets.FOLDERID }}
        overwrite: "true"