name: Build OpenWrt for Banana Pi R4

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.config'
      - '**.img'
      - '**.bin'
      - 'Makefile.local'
      - 'feeds.conf.default'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      kernel_version:
        description: "Kernel version"
        required: true
        default: "6.12"
        type: choice
        options:
          - "6.12"
          - "6.6"
          - "5.15"
      profile:
        description: "Device profile"
        required: true
        default: "bananapi_bpi-r4"
        type: choice
        options:
          - "bananapi_bpi-r4"
          - "bananapi_bpi-r4-poe"

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext zlib1g-dev swig unzip time rsync python3 python3-pip


    - name: Setup OpenWrt feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure OpenWrt for Banana Pi R4
      run: |
        # Copy pre-configured file
        cp bpi-r4-8gb-config .config
        
        # Apply configuration
        make defconfig

    - name: Build OpenWrt
      run: |
        make -j$(nproc) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-bpi-r4-8gb
        path: bin/targets/mediatek/filogic/*
        retention-days: 7

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/targets/mediatek/filogic/*.bin
        generate_release_notes: true
        draft: false
        prerelease: false

    - name: Upload to GitHub Packages
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-bpi-r4-8gb-packages
        path: bin/targets/mediatek/filogic/*.bin
        retention-days: 30